@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package com.hexagram2021.real_peaceful_mode.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;