@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package com.hexagram2021.real_peaceful_mode.server.commands;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;