blank_issues_enabled: false
contact_links:
  - name: Wiki
    url: https://viola-siemens.github.io/pages/real_peaceful_mode/index.html
    about: Here's a wiki in Chinese to describe this mod. You can also search anything for their usage.